#! /bin/bash
#
# Copyright 2019 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ! which autopep8 > /dev/null 2>&1; then
    echo "autopep8 not found!"
    exit 1
fi

if ! which flake8 > /dev/null 2>&1; then
    echo "flake8 not found!"
    exit 1
fi

cd "$(readlink -f $(dirname $0))"
if [ "$1" == "-r" ] || [ "$1" == "--reformat" ]; then
    autopep8 -i -a --global-config /dev/null $(git ls-files '*.py')
fi

flake8 $(git ls-files '*.py')

