#! /bin/bash
#
# Copyright 2019 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -n "$BASH_SOURCE" ]; then
	THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
	THIS_SCRIPT=$0
else
	THIS_SCRIPT="$(pwd)/pyrex-init-build-env"
fi

if [ -z "$ZSH_NAME" ] && [ "$0" = "$THIS_SCRIPT" ]; then
    echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'"
    exit 1
fi

if [ -z "$PYREX_OEROOT" ]; then
	PYREX_OEROOT=$(readlink -f $(dirname $THIS_SCRIPT))
fi

if [ -z "$PYREX_ROOT" ]; then
	PYREX_ROOT=$(dirname $(readlink -f $THIS_SCRIPT))/..
fi

if [ -z "$PYREX_OEINIT" ]; then
	PYREX_OEINIT="$PYREX_OEROOT/oe-init-build-env"
fi

if [ -z "$PYREX_TEMP_FILE" ]; then
	PYREX_TEMP_FILE=$(mktemp -t pyrex.XXXXXX)
fi
PYREX_DEFAULTCONF=$(dirname $(readlink -f $THIS_SCRIPT))/pyrex.ini

unset THIS_SCRIPT

pyrex_cleanup() {
	rm -f "$PYREX_TEMP_FILE"
	unset PYREX_DEFAULTCONF PYREX_OEROOT PYREX_OEINIT PYREX_ROOT PYREX_CONFFILE PYREX_TEMP_FILE pyrex_cleanup
}

# Capture OE Build environment
(
	. $PYREX_OEINIT "$@"
	if [ $? -ne 0 ]; then
		exit 1
	fi

	if [ -z "${PYREXCONFTEMPLATE}" ]; then
		PYREXCONFTEMPLATE="$PYREX_OEROOT/$(cat "$BUILDDIR/conf/templateconf.cfg")/pyrex.ini.sample"
	fi

	# Instruct pyrex.py to output the name of the configuration file to
	# file descriptor 11
	$PYREX_ROOT/pyrex.py capture \
		$PYREX_ROOT \
		$PYREX_DEFAULTCONF \
		$BUILDDIR/conf/pyrex.ini \
		$PYREXCONFTEMPLATE \
		$PYREX_OEROOT \
		-D builddir $BUILDDIR \
		-D oeroot $PYREX_OEROOT \
		11 -- \
		$PYREX_OEINIT "$@" \
		11> $PYREX_TEMP_FILE
)
if [ $? -ne 0 ]; then
	pyrex_cleanup
	return 1
fi
PYREX_CONFFILE=$(cat $PYREX_TEMP_FILE)

# Build Pyrex images
$PYREX_ROOT/pyrex.py build $PYREX_DEFAULTCONF "$PYREX_CONFFILE"
if [ $? -ne 0 ]; then
	pyrex_cleanup
	return 1
fi

# Setup build environment
$PYREX_ROOT/pyrex.py env $PYREX_DEFAULTCONF "$PYREX_CONFFILE" 11 11> $PYREX_TEMP_FILE
if [ $? -ne 0 ]; then
	pyrex_cleanup
	return 1
fi

. $PYREX_TEMP_FILE
if [ $? -ne 0 ]; then
	pyrex_cleanup
	return 1
fi

pyrex_cleanup

# vim: noexpandtab
